version: 0.2

env:
  secrets-manager:
    NPM_TOKEN: /CodeBuild/vivocha-monorepo:NPM_TOKEN
    GH_TOKEN: /CodeBuild/vivocha-monorepo:GH_TOKEN
  git-credential-helper: yes

phases:
  install:
    commands:
      - n 18
  pre_build:
    commands:
      - npm prune
  build:
    commands:
      - npm run build:all
  post_build:
    commands:
      - npm run semantic-release